### ISSUE TITLE
Update examples for v2

### ISSUE THREAD

**Issue by lcgraham** [UT-CHG/BET#167]

**Comment by lcgraham** [comment]
Update to use logging [see logging from multiple modules](https://docs.python.org/2/howto/logging.html#logging-from-multiple-modules)
All print statements within the source have been changed to appropriate logging commands

See #192

**Comment by lcgraham** [comment]
Currently, ``validationExample``, ``nonlinearMap``, ``linearMap``, ``contaminantTransport``, and ``FEniCS`` examples are up to date. @scottw13 are the ``sensitivity`` examples up to date?

None of the examples use logging.

**Comment by scottw13** [comment]
They are not...  they need some attention.  I should be able to get them in
good shape sometime next week.

Scott

**Comment by scottw13** [comment]
In sample.py the method check_num() checks that

input_set._jacobian.shape[0] == input_set.shape._values.shape[0]

But in my examples I do not have the jacobians at every samples, so
_jacobians does NOT have the same length as _values.

How should we fix this?  Maybe jacobians shouldn't be checked here.  Maybe
I should make _jacobians have the same shape[0] as _values, but fill
entries that I dont have jacobians for with Nones? (Not sure I like that
option)  I am just trying to solve the inverse problem after finding the
optimal set of QoIs, I don't even need the jacobians for this but I get
this error when I try to set my_discretization before I solve the inverse
problem,

I guess for now I will just set _jocobians to None at this step since I
don't need them anymore, but that probably isn't the best long term
solution.

Scott

**Comment by lcgraham** [comment]
If I remember correctly you only have Jacobians at the center of point clusters. What about returning a sample set that only has the values for centers since you create and need the Jacobians at all the centers? Or if a full sample set is not needed and only the indices of the optimal QoI then how about returning just the indices?

**Comment by lcgraham** [comment]
Apparently examples are no longer up to date and need to be rechecked.

**Comment by lcgraham** [comment]
@eecsu can you submit a pull-request with the examples that you've updated? If I recall correctly you've made significant changes which haven't been pulled in yet.

**Comment by lcgraham** [comment]
Note that recent pull-requests have updated examples.

**Comment by eecsu** [comment]
Yeah, I am working with Pilosov on these. He is getting the hang of BET
now. I have some other things to do with the FEniCS example in order to use
launcher, and also do the KL stuff just once. Should have some time to
clean this all up in the next two days. Will also get to your pull request
soon.

**Comment by lcgraham** [comment]
Sounds great. Thanks for the update!

**Comment by lcgraham** [comment]
@eecsu, @mpilosov when this is done feel free to close the issue.

**Comment by eecsu** [comment]
I have updated the documentation for the linear, nonlinear, validation, and both FEniCS examples. 

For the examples others wrote, they may want to update in a similar style that breaks down according to steps like how I did it.

On the gh-pages, if you access an example through the "List of all examples" on the side panel, then this creates a table of contents for easy navigation through the steps.

**Comment by lcgraham** [comment]
This task include updating the *.rst files. I need to update these for some of the examples I have written. @smattis can you check the associated *.rst files for the contaminant transport example?

**Comment by eecsu** [comment]
@lcgraham did you look over the changes to the ADCIRC from file documentation that I changed? I tried to make at least the first set of examples consistent with the format of outlining the steps we are doing in the basic algorithm of solving a stochastic inverse problem. The examples themselves were updated slightly with visualization of domains showing up in the first set of scripts (which allowed me to remove the documentation that just focused on the documentation since it was basically absorbed into these files).

@scottw13 still needs to provide documentation for the sensitivity examples. I can probably take a first stab at it and have him look it over to make sure I am understanding everything correctly. Probably a good exercise for me to go through his examples more carefully anyway.

**Comment by scottw13** [comment]
Troy if you want to take a first stab at these that's fine by me.  Let me
know how it goes or if you have any questions.

Scott

**Comment by lcgraham** [comment]
@eecsu I really like what you did with teh first set of ADCIRC examples. So
much so that I want to copy your lead for the second set of ADCIRC examples
(the Q_*.py ones).

On Thu, Jun 30, 2016 at 1:00 PM Scott Walsh <notifications@github.com>
wrote:

> Troy if you want to take a first stab at these that's fine by me. Let me
> know how it goes or if you have any questions.
>
> Scott
>
> On Thu, Jun 30, 2016 at 10:58 AM, Troy Butler <notifications@github.com>
> wrote:
>
> > @lcgraham <https://github.com/lcgraham> did you look over the changes to
> > the ADCIRC from file documentation that I changed? I tried to make at
> least
> > the first set of examples consistent with the format of outlining the
> steps
> > we are doing in the basic algorithm of solving a stochastic inverse
> > problem. The examples themselves were updated slightly with visualization
> > of domains showing up in the first set of scripts (which allowed me to
> > remove the documentation that just focused on the documentation since it
> > was basically absorbed into these files).
> >
> > @scottw13 <https://github.com/scottw13> still needs to provide
> > documentation for the sensitivity examples. I can probably take a first
> > stab at it and have him look it over to make sure I am understanding
> > everything correctly. Probably a good exercise for me to go through his
> > examples more carefully anyway.
> >
> > —
> > You are receiving this because you were mentioned.
> > Reply to this email directly, view it on GitHub
> > <https://github.com/UT-CHG/BET/issues/167#issuecomment-229721320>, or
> mute
> > the thread
> > <
> https://github.com/notifications/unsubscribe/AFMm2toD9uUxxSy_hqFg5EH4BncQXxRxks5qQ_XBgaJpZM4H2mBx
> >
> > .
> >
>
> —
> You are receiving this because you were mentioned.
> Reply to this email directly, view it on GitHub
> <https://github.com/UT-CHG/BET/issues/167#issuecomment-229721908>, or mute
> the thread
> <https://github.com/notifications/unsubscribe/AC3o7Y5hULo2_ek61xlpZGATQXugvSRQks5qQ_ZEgaJpZM4H2mBx>
> .
>
-- 

Lindley Graham, Ph.D. 2015
