### ISSUE TITLE
plotP updates for parallel

### ISSUE THREAD

**Issue by eecsu** [UT-CHG/BET#199]
computing 2d or 1d marginals in parallel results in plots of densities that integrate to the number of processors used not 1. This needs to be fixed if people want to make use of "raw" non-smoothed marginal plots that are generated in parallel.

**Comment by lcgraham** [comment]
In version 1.0 both ``calculate_1D_marginal_probs`` and ``calculate_2D_marginal_probs`` were both created to work with the results for ``calculateP.calculateP.prob_emulated`` the result of which is a localized ``P`` on ``lambda_emulated``. This way we never have to globalize ``P`` even when we want to create marginals for plotting results.

When ``calculate_1D_marginal_probs`` and ``calculate_2D_marginal_probs`` were updated this did not translate over. I am updating the tests, methods, and docstrings so that these methods use the localized P not the globalized P.
