### ISSUE TITLE
shape of _jacobians not consistent

### ISSUE THREAD

**Issue by scottw13** [UT-CHG/BET#212]
In the linear sensitivity examples the _jacobians.shape[0] != _values.shape[0] because we only approximate jacobians at the centers, not at all of the samples.  Maybe work with a input_samples_centers sample_set tofix this issue.  Right now I just set _jacobians to None when I am don with them...

**Comment by lcgraham** [comment]
I think this would be solved by modifying gradients.py by 1) either take as an argument an input set or a discretization object, if there is a method takes both an input set and an output set it should be modified to only take a discretization; 2) all outputs should either be sample_set objects, discretization objects, or nothing instead of arrays; 3) if a method calculates gradients for a set of "centers" a new sample_set object or discretization should be created and retuned containing only the samples which have Jacobians. If number 3 is done then all of the methods in chooseQoIs.py can assume all samples should have gradient information and num_centers need never be determined as that is simply the result of check_num(). You might want to look at some of the methods in the other subpackages for how this is done. If you don't have time I can code up a suggestion and you can let me know what you think.

**Comment by scottw13** [comment]
That all makes sense.  Ill look at the other subpackages and make these changes.

**Comment by lcgraham** [comment]
Excellent!

**Comment by lcgraham** [comment]
Once #209 is merged then only the sensitivity examples need to be updated.
