### ISSUE TITLE
sample.py: provide option to use emulated_sample_set in estimate_volume

### ISSUE THREAD

**Issue by mpilosov** [UT-CHG/BET#227]
This limitation is documented here: http://ut-chg.github.io/BET/bet.html#bet.sample.sample_set_base.estimate_volume
and is an enhancement I could personally use. I would be willing to tackle it, but I could use advice about the parallelized part of the code. 
PS typo in description of estimate_volume: "faction" instead of "fraction"

**Comment by lcgraham** [comment]
I think this can be solved by adding new methods to both `sample_set_base` and `discretization`:

    sample_set_base.estimate_volume_emulated(emulated_sample_set)
    discretization.estimate_input_volume_emulated(self)
    discretization.estimate_output_volume_emulated(self)

Before adding the second two methods `bet.calculateP.simpleFunP` should be checked to prevent redundancy.

**Comment by smattis** [comment]
`calculateP.prob_mc` (which needs to be renamed when I have chance) does calculate volumes from emulated points

**Comment by mpilosov** [comment]
@smattis I'm taking a second look at that function and it appears that in order for it to be used, one must first use ```set_emulated_input_sample_set```
whereas what I was thinking is that if a user calls ```estimate_volume``` with some (potentially large) number of samples, why aren't those samples written to ```emulated_input_sample_set``` since we generated them anyway? Or on the flipside, if someone defines  ```emulated_input_sample_set``` first and then calls  ```estimate_volume```, why should all those samples be re-created when a perfectly valid set we could use is sitting in ```_emulated_input_sample_set```?

**Comment by lcgraham** [comment]
@smattis true, and if you want to use those emulated points for another set of input samples then you can just create a new discretization and copy them over. I'm thinking of the case where you might want to use the same emulated points to estimate volumes for different sample sets. I'm going to propose a pull-request with a proposed modification...

@mpilosov Those samples aren't written to ``emulated_input_sample_set`` because often we don't need or want to save those samples for future use, _especially_ for a potentially large number of emulated samples.

Also an ``_emulated_input_sample_set`` is only associated with a ``discretization`` object NOT with a ``sample_set_object``. If some one has already defined ``_emulated_input_sample_set`` they should use ``bet.calculateP.prob_mc`` like @smattis said which uses the emulated samples to estimate the volume.
