### ISSUE TITLE
calculate marginals not working -- bug in histogramdd (I think)

### ISSUE THREAD

**Issue by eecsu** [UT-CHG/BET#239]
Hey @lcgraham and @smattis, I am working with @mpilosov and we think that numpy's ``histogramdd`` is buggy. We are seeing some pretty bad incorrect binning. I think we should replace this with nearest neighbor searches like we have elsewhere in the code. Just provide a sample_set of the bin centers and then create a bin_ptr to compute the marginals. At least we know this works. The current binning problem with ``histogramdd`` is odd. @mpilosov can send you the example so you can see the issue if you like. I am definitely in favor of changing this.

**Comment by smattis** [comment]
Can you produce an example where the binning appears to be wrong?

On Tue, Jun 28, 2016 at 10:20 PM, Troy Butler <notifications@github.com>
wrote:

> Hey @lcgraham <https://github.com/lcgraham> and @smattis
> <https://github.com/smattis>, I am working with @mpilosov
> <https://github.com/mpilosov> and we think that numpy's histogramdd is
> buggy. We are seeing some pretty bad incorrect binning. I think we should
> replace this with nearest neighbor searches like we have elsewhere in the
> code. Just provide a sample_set of the bin centers and then create a
> bin_ptr to compute the marginals. At least we know this works. The current
> binning problem with histogramdd is odd. @mpilosov
> <https://github.com/mpilosov> can send you the example so you can see the
> issue if you like. I am definitely in favor of changing this.
>
> —
> You are receiving this because you were mentioned.
> Reply to this email directly, view it on GitHub
> <https://github.com/UT-CHG/BET/issues/239>, or mute the thread
> <https://github.com/notifications/unsubscribe/AA84CevIBiI1YiR64UCtCX_F2OV_xoknks5qQeRsgaJpZM4JAvEr>
> .
>



-- 
Postdoctoral Research Fellow
Institute for Computational Engineering and Sciences
The University of Texas at Austin

**Comment by mpilosov** [comment]
I have one that is perhaps unnecessarily complex in my fork of BET under examples/estimateDist/run_est.py
I am working on a much simpler one but so far can't quite get it and have a workshop to attend this morning so I won't be able to work on it until the afternoon. If you want to try the current example, read on.

Check out the print-out that shows up and scroll to the top of it. Compare the 3x3 reference marginal (which is correct because the center of the bins are the samples we are binning) to the estimate of this distribution  using 40 random samples. We also print the io_ptr and probabilities. Matching these to each other, we find that as long as each bin gets at least one sample (which with the random seed I used, this example will). Tracking these indices and adding up the weights manually, we find that the reference marginal should have been recreated but somehow the marginals binning procedure (histogramdd) is not computing the correct weights.

**Comment by mpilosov** [comment]
phew. right in time for my workshop, I got a simple script working.
Check out ```histogram_test.py ``` in the recover branch on my fork. It's the only file you'll need to run to see the problem. I use an identity map so that the inverse problem is truly trivial.

I don't know what's standard operating procedure here, so apologies if this is in bad taste, but here's my code pasted so you don't even have to go rummaging around in my fork:
`

import numpy as np
import bet.postProcess as postProcess
import bet.calculateP.simpleFunP as simpleFunP
import bet.calculateP.calculateP as calculateP
import bet.postProcess.plotP as plotP
import bet.postProcess.plotDomains as plotD
import bet.postProcess.postTools as postTools
import bet.sample as samp
import bet.sampling.basicSampling as bsam
import bet.sensitivity.gradients as grad
import bet.sensitivity.chooseQoIs as cqoi
import bet.Comm as comm
np.random.seed(40)

def identity_model(parameter_samples):
    Q_map = np.array([[1.0, 0.0], [0.0, 1.0]])
    QoI_samples = np.dot(parameter_samples, np.transpose(Q_map))
    return QoI_samples

num_samples_param_space = 40
dim_input = 2
grid_cells_per_dim = 3 # discretization of data space (regular grid)
dim_range = [0.0, 1.0]
alpha = 1
beta = 1
num_samples_emulate_data_space = (grid_cells_per_dim**dim_input)*100

eye = bsam.sampler(identity_model)

# create partition and emulation sets
Partition_Set = samp.sample_set(dim_input)
Partition_Set.set_domain(np.repeat([dim_range], dim_input, axis=0))
Partition_Set = bsam.regular_sample_set(Partition_Set, num_samples_per_dim = np.repeat(grid_cells_per_dim, dim_input, axis=0))

Emulated_Set = samp.sample_set(dim_input)
Emulated_Set.set_domain(np.repeat([dim_range], dim_input, axis=0))
# Emulation from true distribution 
Emulated_Set.set_values(np.array( np.transpose([ np.random.beta(a=alpha, b=beta,
            size=num_samples_emulate_data_space) for i in range(dim_input) ]) ))


Reference_Set = samp.sample_set(dim_input)
Reference_Set.set_domain(np.repeat([dim_range], dim_input, axis=0))
Reference_Set = bsam.regular_sample_set(Reference_Set, num_samples_per_dim = np.repeat(grid_cells_per_dim, dim_input, axis=0))

Reference_Discretization = eye.compute_QoI_and_create_discretization(Reference_Set)
# Reference_Discretization._input_sample_set.estimate_volume_mc() # The MC assumption is true.
Reference_Emulation = eye.compute_QoI_and_create_discretization(Emulated_Set)


simpleFunP.user_partition_user_distribution(Reference_Discretization, 
                                            Reference_Discretization, 
                                            Reference_Emulation)

# set probabilities - the map was the identity, so the inverse problem is trivial
Reference_Discretization._input_sample_set.set_probabilities(Reference_Discretization._output_probability_set._probabilities)

# compute reference marginal
(bins, ref_marginals2D) = plotP.calculate_2D_marginal_probs(Reference_Discretization._input_sample_set, nbins = grid_cells_per_dim)
print 'Reference Marginal:'
print ref_marginals2D[(0,1)]

print '\nReference Probabilities:'
print Reference_Discretization._input_sample_set._probabilities



Input_Samples = samp.sample_set(dim_input)
Input_Samples.set_domain(np.repeat([dim_range], dim_input, axis=0))
Input_Samples = bsam.random_sample_set('random', Input_Samples, num_samples = num_samples_param_space)
# Input_Samples = bsam.regular_sample_set(Input_Samples, num_samples_per_dim = np.repeat(grid_cells_per_dim, dim_input, axis=0))
Input_Samples.estimate_volume_mc()

# Solve Inverse Problem
My_Discretization = eye.compute_QoI_and_create_discretization(Input_Samples)
Partition_Discretization = eye.compute_QoI_and_create_discretization(Partition_Set)
Emulated_Discretization = eye.compute_QoI_and_create_discretization(Emulated_Set)

simpleFunP.user_partition_user_distribution(My_Discretization,
                                            Partition_Discretization,
                                            Emulated_Discretization)
calculateP.prob(My_Discretization)                                            

print '\nInverse Problem, Probabilities:'
print My_Discretization._input_sample_set._probabilities_local
print 'Pointer:'
print My_Discretization._io_ptr_local
print '\nInvere Solution Marginal'
# print marginals for comparison
(bins, marginals2D) = plotP.calculate_2D_marginal_probs(My_Discretization._input_sample_set, nbins = grid_cells_per_dim)
print marginals2D[(0, 1)]
print '\n'
`

**Comment by eecsu** [comment]
I think I figured this out thanks to Varis pointing out an error in basic
arithmetic of dividing the domain into uniform cells. Will work on in a bit
and see if I can fix this.

**Comment by smattis** [comment]
Hey. Just spent awhile looking at this. The problem is not in calculating the marginals. I just modified the above script and calculate the marginals in the most naive way possible and they check out.

```
import numpy as np
import bet.postProcess as postProcess
import bet.calculateP.simpleFunP as simpleFunP
import bet.calculateP.calculateP as calculateP
import bet.postProcess.plotP as plotP
import bet.postProcess.plotDomains as plotD
import bet.postProcess.postTools as postTools
import bet.sample as samp
import bet.sampling.basicSampling as bsam
import bet.sensitivity.gradients as grad
import bet.sensitivity.chooseQoIs as cqoi
import bet.Comm as comm
np.random.seed(40)

def identity_model(parameter_samples):
    Q_map = np.array([[1.0, 0.0], [0.0, 1.0]])
    QoI_samples = np.dot(parameter_samples, np.transpose(Q_map))
    return QoI_samples

num_samples_param_space = 40
dim_input = 2
grid_cells_per_dim = 3 # discretization of data space (regular grid)
dim_range = [0.0, 1.0]
alpha = 1
beta = 1
num_samples_emulate_data_space = (grid_cells_per_dim**dim_input)*100

eye = bsam.sampler(identity_model)

# create partition and emulation sets
Partition_Set = samp.sample_set(dim_input)
Partition_Set.set_domain(np.repeat([dim_range], dim_input, axis=0))
Partition_Set = bsam.regular_sample_set(Partition_Set, num_samples_per_dim = np.repeat(grid_cells_per_dim, dim_input, axis=0))

Emulated_Set = samp.sample_set(dim_input)
Emulated_Set.set_domain(np.repeat([dim_range], dim_input, axis=0))
# Emulation from true distribution 
Emulated_Set.set_values(np.array( np.transpose([ np.random.beta(a=alpha, b=beta,
            size=num_samples_emulate_data_space) for i in range(dim_input) ]) ))


Reference_Set = samp.sample_set(dim_input)
Reference_Set.set_domain(np.repeat([dim_range], dim_input, axis=0))
Reference_Set = bsam.regular_sample_set(Reference_Set, num_samples_per_dim = np.repeat(grid_cells_per_dim, dim_input, axis=0))

Reference_Discretization = eye.compute_QoI_and_create_discretization(Reference_Set)
# Reference_Discretization._input_sample_set.estimate_volume_mc() # The MC assumption is true.
Reference_Emulation = eye.compute_QoI_and_create_discretization(Emulated_Set)


simpleFunP.user_partition_user_distribution(Reference_Discretization, 
                                            Reference_Discretization, 
                                            Reference_Emulation)

# set probabilities - the map was the identity, so the inverse problem is trivial
Reference_Discretization._input_sample_set.set_probabilities(Reference_Discretization._output_probability_set._probabilities)

# compute reference marginal
(bins, ref_marginals2D) = plotP.calculate_2D_marginal_probs(Reference_Discretization._input_sample_set, nbins = grid_cells_per_dim)
print 'Reference Marginal:'
print ref_marginals2D[(0,1)]

print '\nReference Probabilities:'
print Reference_Discretization._input_sample_set._probabilities



Input_Samples = samp.sample_set(dim_input)
Input_Samples.set_domain(np.repeat([dim_range], dim_input, axis=0))
Input_Samples = bsam.random_sample_set('random', Input_Samples, num_samples = num_samples_param_space)
# Input_Samples = bsam.regular_sample_set(Input_Samples, num_samples_per_dim = np.repeat(grid_cells_per_dim, dim_input, axis=0))
Input_Samples.estimate_volume_mc()

# Solve Inverse Problem
My_Discretization = eye.compute_QoI_and_create_discretization(Input_Samples)
Partition_Discretization = eye.compute_QoI_and_create_discretization(Partition_Set)
Emulated_Discretization = eye.compute_QoI_and_create_discretization(Emulated_Set)

simpleFunP.user_partition_user_distribution(My_Discretization,
                                            Partition_Discretization,
                                            Emulated_Discretization)
calculateP.prob(My_Discretization)                                            

print '\nInverse Problem:\n Probabilities:'
print My_Discretization._input_sample_set._probabilities_local
print 'Pointer:'
print My_Discretization._io_ptr_local
print '\nInverse Solution Marginal'
# print marginals for comparison
(bins, marginals2D) = plotP.calculate_2D_marginal_probs(My_Discretization._input_sample_set, nbins = grid_cells_per_dim)
print marginals2D[(0, 1)]
print '\n'

num = My_Discretization._input_sample_set.check_num()
marg_check = np.zeros((grid_cells_per_dim, grid_cells_per_dim))

print "\nCheck Inverse Solution Marginal Using Naive Binning"
for i in range(num):
    for j in range(grid_cells_per_dim):
        for k in range(grid_cells_per_dim):
            val = My_Discretization._input_sample_set._values[i,:]
            if val[0] >= bins[0][j] and val[0] < bins[0][j+1] and val[1] >= bins[1][k] and val[1] < bins[1][k+1]:
                marg_check[j,k] += My_Discretization._input_sample_set._probabilities[i]
print marg_check
```

**Comment by smattis** [comment]
@eecsu and @mpilosov In the future, when raising issues, try to have a concise example that illustrates the issue, rather than a script for a whole problem and suggesting where the issue probably is. I did a sanity check on the marginal calculations in a few lines of code:

```
import bet.sample as samp
import bet.postProcess.plotP as plotP
import numpy as np

s = samp.sample_set(3)
s.set_domain(np.array([[0.0, 1.0],
                       [0.0, 1.0],
                       [0.0, 1.0]]))
vals = np.array([[0.1, 0.1, 0.1],
                 [0.8, 0.1, 0.1],
                 [0.1, 0.8, 0.1],
                 [0.8, 0.8, 0.1]])
s.set_values(vals)
prob = np.array([0.7, 0.1, 0.1, 0.1])
s.set_probabilities(prob)
(bins, marg) = plotP.calculate_2D_marginal_probs(s, nbins=2)
```
and everything was as I expected. An example like this where the binning is being messed up is what I would expect in the future for an issue like this to be raised.

**Comment by mpilosov** [comment]
I see. so the issue is in the reference marginal computation somewhere. I'll talk to Troy and see what's up.
Apologies for the bad case example, and thanks for your help. It was and is always much appreciated.
