### ISSUE TITLE
Tests not passing

### ISSUE THREAD

**Issue by mathematicalmichael** [UT-CHG/BET#294]
I have been completely unable to find a suitable environment in which the tests pass. Not on my macbook (including old environments where they did pass), nor in a new Ubuntu 18 container with a fresh install of python 2.7.

@smattis any luck getting `nosetests` to run successfully? In what environments/builds? 

Here are some of the relevant errors from what I can tell that are triggering it

```
/Users/Imogen/Packages/BET/bet/sensitivity/chooseQoIs.py:121: RuntimeWarning: invalid value encountered in divide
  normgiperp = muG / muGi
/Users/Imogen/anaconda3/envs/py27/lib/python2.7/site-packages/scipy/stats/stats.py:584: RuntimeWarning: divide by zero encountered in double_scalars
  return size / np.sum(1.0/a, axis=axis, dtype=dtype)
```
@scottw13 do tests pass for you?

**Comment by scottw13** [comment]
I did not reinstall, but I remember always seeing this error.  Like Steve
said, it doesn’t cause the tests to fail.  It happens when the gradient
vectors are linearly dependent.

Scott

**Comment by mathematicalmichael** [comment]
Well that aside, I believe those are being caught as warnings, the test failing is not per-say acceptable. Just curious if anyone has them passing in any capacity at all.

**Comment by smattis** [comment]
Did you read my comment? All tests still pass for me, so I have no idea
what you’re talking about. Can you post the output from running nosetests?

**Comment by mathematicalmichael** [comment]
@smattis no, sorry I missed it (didn't go to email for some reason but Scott's did). what is your environment? 

What I pasted was just some of the output. at the end, I still receive errors. 
Fresh Python 2 build inside of Docker using jupyter/docker-stacks:
```
(python2) jovyan@855585a15694:~/work/BET$ which python
/opt/conda/envs/python2/bin/python
(python2) jovyan@855585a15694:~/work/BET$ python --version
Python 2.7.15
(python2) jovyan@855585a15694:~/work/BET$ which nosetests
/opt/conda/envs/python2/bin/nosetests
```

So, everything is fine, ran `python setup.py install` and then `nosetests`...

```
Ran 79 tests in 0.627s

FAILED (errors=13)
```

The errors are different on my personal laptop (I think it's just 3 errors instead of 13), but the ones in this fresh environment (Ubuntu 18) show

```
======================================================================
ERROR: Failure: SyntaxError (Non-ASCII character '\xe2' in file /opt/conda/envs/python2/lib/python2.7/site-packages/scipy-1.2.0-py2.7-linux-x86_64.egg/scipy/stats/_continuous_distns.py on line 3346, but no encoding declared;
```

stuff along those lines. Which... is a `scipy` issue, but seeing as it's specified in `setup.py`, I was confused as to why I'm seeing it (and Troy too) and you are not. So... that is one env in which I cannot get this to build.

Running on my laptop (which produced what I pasted originally).. besides FutureWarnings, I see the final message as `FAILED (SKIP=8, errors=3)`, and the errors relating to matplotlib and MacOSX backends. I know that's not a major issue, but an end-user still would expect tests to pass, not error out. Why are plotting functions being tested? 

Moreover, the clean UNIX environment at the very least won't produce plotting framework issues and still doesn't pass (seemingly due to scipy?). If I was someone trying this software out for the first time, I would presume it was broken after these two attempts, which has the opposite effect of what `nosetests` are supposed to accomplish (a sense of safety/stability).

Also, correct me if I'm wrong, but shouldn't the test be changed or an error exception be added to handle division by zero? Seems inappropriate to see that as part of "passing" tests. (in the same spirit of end-user experience). 

I'm planning to do the upgrade to Python 3 and really want to make sure I'm starting from a stable starting point, and that nosetests show nothing but `............... OK`.

**Comment by mathematicalmichael** [comment]
at the very least, the `scipy` issue needs to be addressed with a version-lock in `setup.py`. What `scipy` version are you using, @smattis? (I'm far less concerned with the macbook matplotlib errors, but the question of why test plotting remains, since we do want this to pass on macbooks, no?).

**Comment by smattis** [comment]
@mathematicalmichael  It seems like your issues are arising scipy v1.2 which was released in December. I am doing my builds using conda, and they are using scipy v1.1 as the default version of scipy for python 2.7. I just merged something to master that takes care of some really minor things that were creating errors with newer versions of numpy. I included a version lock for scipy, numpy, and matplotlib for the time being, because it seems like figuring out the scipy v1.2 issues might be a little challening. 

Now, everything passes with a pretty standard conda build:
```bash
conda create -n environment_name python=2.7
conda install pip nose numpy scipy matplotlib
pip install pyDOE mpi4py
```
I am pretty sure that it should work ok with the version locks in `setup.py` now with your "clean" environment. I suppose I could suggest a conda build in the Readme file. Conda also works well for setting up Docker containers.

There are still a few warnings when the tests are run now, but they are really minor and are in rarely-used routines. These are hard to avoid. I could suppress them, but that could cause problems down the line. One of the main reasons we have all of these tests is for continuous integration, so having as much coverage as possible is what we strive for. I think it is really important that we test the plotting tools with unit tests. Also, matplotlib tends to change pretty often, so it is good to test these routines to make sure that they are not breaking. I also have a Mac, and with my conda all of the plotting tests pass. I'm guessing that the matplotlib backend on your Mac is what is causing issues. This is a common problem.

It's difficult to write packages that work with all environments. That is why package managers like conda are nice for creating a local environment that works great for the application that you want to use. Looking at .yml files for Travis CI for many scientific packages, I see that now most people writing python packages are really only testing a nice clean conda environment, which is what we are doing. 

I appreciate the concern, and thanks for realizing that the newest scipy version breaks some stuff. I just set up Travis to run weekly cron jobs to catch stuff like this with problems arising from version updates of dependencies. If you can get the code updated for python 3, that would be great. In the future, you can check the build icon on the Readme, and that shows whether or not it is passing its weekly test build on a conda environment. If it fails, we all get an email. I am mostly interested that it keeps passing on that environment than spending a ton of time making sure it passes every test on every environment.

**Comment by mathematicalmichael** [comment]
Thanks, @smattis! 
I've also been building with conda, the http://math.computer setup is all dockerize, both hub and single-user servers, so it was the natural choice. That's the environment I care most about. Having it work locally isn't too much of a concern (I've encountered the framework issue before, know it's not a problem). 

I will get it converted to Python 3 next semester. Hopefully sooner than later. Thank you again for getting it to a place where I can pick up from (I will try to resolve those scipy issues in the upgrade). Apologies in advance for the issues/PR's that are forthcoming. 

However... I followed the instructions you pasted (after pulling the latest changes) and was still coming up against the plotting errors.
```
FAILED (SKIP=8, failures=12)
``` 

all `failures` relating to 

```
  File "/opt/conda/envs/python2/lib/python2.7/site-packages/numpy/testing/_private/utils.py", line 414, in assert_equal
    raise AssertionError(msg)
```

I've frankly had zero trouble installing anything in fresh conda environments before, so I'm highly perplexed right now because the builds ARE passing, seem to match environments (minus maybe the unix distro, which shouldn't matter?), but we're getting different results.

I can see that the plotting errors are the problem but how come the build passes? There can't be any `failures` in a pass, can there? Again, sorry for the barrage of questions, but once we're stable and I understand the CI aspect, I'll be able to start the update in earnest.

**Comment by smattis** [comment]
Right, there can be no failures in a pass. 

Can you see what the matplotlib backend is with by doing

``
>>> import matplotlib
>>> print (matplotlib.rcParams['backend'])
``

**Comment by mathematicalmichael** [comment]
Looking a little deeper, all errors are of the following format:

```
try:
            plotP.plot_1D_marginal_probs(marginals, bins, self.samples,
                                         filename = "file", interactive=False)
            go = True
        except (RuntimeError, TypeError, NameError):
            go = False
        nptest.assert_equal(go, True)
```

So, has something changed in `nptest`? Is the version lock of matplotlib the issue? From what I can tell, this test simply tests the plotting code for success.

If I may provide some perspective: one thing I have noticed in some repositories is a complete shunning of any custom plotting functionality. In effect, it is often left to the user to customize visualizations to their liking rather than learning (yet another) new custom wrapper around pyplot. Plotting code is splayed out in example files (yes, annoying), but it is the responsibility of the user to use the plotting backends they want to (many people now use plotly, for example, especially with it's appealing feature set). 

I see the point of testing plotting, but I'm not so sure I think it's a long-term sustainable solution to package in a custom matplotlib wrapper as part of the package. Our main goal is to publish the novel mathematical method, which at the end of the day has nothing to do with plotting (as helpful as that is). I encountered this a lot with the Jupyter Project, where they basically leave a bunch of components up to the end-user to figure out, publishing separate repos for all the various options, rather than package in some default choices. Just putting it out there, especially since matplotlib is kind of unstable.

**Comment by mathematicalmichael** [comment]
@smattis looks like we're on `Qt5`

```
In [1]: import matplotlib

In [2]:  print (matplotlib.rcParams['backend'])
Qt5Agg
```

**Comment by smattis** [comment]
Can you try
```
import matplotlib.pyplot as plt
plt.switch_backend('Agg')
```
and rerun the tests?

**Comment by mathematicalmichael** [comment]
```
In [1]: import matplotlib.pyplot as plt
   ...: plt.switch_backend('Agg')
   ...:

In [2]: QXcbConnection: Could not connect to display
Aborted (core dumped)
```
was the result, so that didn't change the tests.

I tried `export DISPLAY=0` (and `:0`) but still got `Could not connect to display` ... 
(again, dockerized environment, I'm sure that's related).

**Comment by mathematicalmichael** [comment]
```
In [1]: import matplotlib.pyplot as plt
   ...: plt.switch_backend('Agg')
   ...:

In [2]: QXcbConnection: Could not connect to display
```

was addressed with `export QT_QPA_PLATFORM='offscreen'`

Then I re-ran nosetests. Same errors.
Figured it couldn't hurt to try `python setup.py install` as well, but that didn't help.

**Comment by mathematicalmichael** [comment]
running individual tests, I can see that switching the backend in `ipython` does not propagate to the test. 

```
matplotlib: DEBUG: CACHEDIR=/home/jovyan/.cache/matplotlib
matplotlib.font_manager: DEBUG: Using fontManager instance from /home/jovyan/.cache/matplotlib/fontList.json
matplotlib.backends: DEBUG: backend Qt5Agg version 5.6
--------------------- >> end captured logging << ---------------------
```

**Comment by smattis** [comment]
@mathematicalmichael Sorry for taking awhile to get back to you. This definitely makes sense to me that the problem was the matplotlib backend in a dockerized build. You need to have a `DISPLAY` environment variable properly defined or any plotting will probably give errors unless a very basic backend like Agg is used.

I agree that to make publication quality figures, you probably need to modify the plotting functions that are included in the package. Still, it is quite nice to have some default plotting tools to make initial visualization fast and easy. One idea would be to set an exception to not run the plotting tests if the `DISPLAY` environment variable is not set and instead create a warning. I think that this might be the easiest solution to have these functions still be tested most of the time. Am I right that in your container right now `DISPLAY` is not set or set to null?

Regarding the parallel tests, I really don't know why these would be failing. It is probably fixable. What is your scipy version?

**Comment by mathematicalmichael** [comment]
so, I tried setting the display variables but couldn't quite get it to work. `export DISPLAY=0` (and `:0` both failed to fix the tests with the default backend). 

I like your idea of overriding the tests, but I do plan on eventually making sure that `PyQt5` can serve as our backend, since this is what ships with Conda. I'm sure it is indeed the `DISPLAY` issue, but how could I address it other than the above? Do I need to set it to `1`? Had a hard time finding good answers online, particularly since Docker is involved. 

`scipy` needed to be at `1.1.0`, so that's where I'm at right now. I will address getting it to `1.2.0` soon.

I think the parallel tests might have been because I was running on a single-threaded machine. I'll make sure to run a more thorough investigation tomorrow on a multi-threaded one.

**Comment by mathematicalmichael** [comment]
no, I understood. Apologies for not being clear. What I was asking was _what steps should I take on my dockerized machine to export DISPLAY variables in a way that may allow the default tests to pass?_ 
Nothing is set right now inside the default container.

**Comment by mathematicalmichael** [comment]
update: trying some things along the lines of "running graphical applications from docker containers." since that seems to be the issue. I'll investigate... the good news is that these issues are unrelated to the tests themselves.

**Comment by smattis** [comment]
Ok. Good.
