### ISSUE TITLE
linting questions

### ISSUE THREAD

**Issue by mathematicalmichael** [UT-CHG/BET#306]
Methods in classes are sometimes separated by a whitespace, other times not. As I'm going through writing new functions based on existing ones, I'm finding these sorts of things (e.g. in `sample.py`) and am happy to correct them in an independent PR. What is the preferred whitespace formatting? Ex: [line 34](https://github.com/UT-CHG/BET/blob/10f6e8da73f0fe82faf01aab476eae8a7031dd60/test/test_sample.py#L34) and [line 57](https://github.com/UT-CHG/BET/blob/10f6e8da73f0fe82faf01aab476eae8a7031dd60/test/test_sample.py#L57) and [165](https://github.com/UT-CHG/BET/blob/10f6e8da73f0fe82faf01aab476eae8a7031dd60/test/test_sample.py#L165)

likewise, test classes are capitalized with `Test_class_name` and then their subsequent methods are mixtures of uppercase and lowercase spellings (e.g. functions in `test_sample.py`). I am assuming this is due to multiple authors. E.g. [line 460](https://github.com/UT-CHG/BET/blob/10f6e8da73f0fe82faf01aab476eae8a7031dd60/test/test_sample.py#L460) vs [line 424](https://github.com/UT-CHG/BET/blob/10f6e8da73f0fe82faf01aab476eae8a7031dd60/test/test_sample.py#L424) 

Again, happy to fix it but I'd like confirmation that all methods in capitalized test classes should be named with `test_method_name` format (`_` between words and lowercase names). 

@lcgraham suggestions on how to proceed (either manually or otherwise)?

**Comment by lcgraham** [comment]
Hi Michael,

I think my preference would be whatever PEP8 recommends. I try to separate
methods in the same class by a single space, and methods in difference
classes or classes by two spaces.

Yes, that's probably due to multiple authors. I would double check that the
capitalization isn't for the nosetests. You should feel free and empowered
to fix it if you'd like to.

Thanks for being so detail oriented! You might be able to use an automatic
linter to reformat things. I've used autopep in the past, but there might
be more current solutions out there. I bet there's a plugin for
Sublime/vim/your-IDE/editor of choice.

Cheers,
Lindley

**Comment by mathematicalmichael** [comment]
- [ ] whitespace
- [ ] capitalization styling: TestClass, test_method
- [ ] `setUp` => `setup` ?? 
- [ ] Why no decorators? [nose documentation](https://nose.readthedocs.io/en/latest/writing_tests.html#test-packages)
- [ ] autopep

**Comment by mathematicalmichael** [comment]
@lcgraham wow! autopep8 did both the capitalization thing and the whitespace. absolutely going to run it on the files and submit a PR for that. like... now.
