### ISSUE TITLE
data-consistent methods

### ISSUE THREAD

**Issue by smattis** [UT-CHG/BET#365]
Clean up and merge in @mathematicalmichael 's data-consistent methods for version 3.

**Comment by mathematicalmichael** [comment]
- [ ] line up `dev` branch with master, then merge forked copy changes into there.

- [ ] docstrings

**Comment by smattis** [comment]
sounds good

**Comment by smattis** [comment]
Hey @mathematicalmichael. I'm sure you're really busy, but I was wondering if there is any progress on this front.

**Comment by mathematicalmichael** [comment]
Yes! It’s in good shape now, got scipy upgraded, and changed to pickling files. tested extensively on both old and new code. Only changes i had to make in order to load old saved discretizations was sometimes stripping .mat file endings. Think it’s something we can code a check to fix, since extensions are meaningless anyway. 

Ran parallel testing up to eight processors with all those changes about two weeks ago. Been running my develop branch build on python scripts from two years ago (god bless git history!) to recreate fresh experiments all day with a fenics model in a minimal docker container (as opposed to the beefy one I normally develop on). No hiccups at this point. 

So, pretty much ready to merge the work on my fork tomorrow. Very confident in that. 

I will ping you tomorrow with a status update.

**Comment by mathematicalmichael** [comment]
PS i have a bit of headway on this, but if we can use BET to improve existing classifier/clustering algorithms, I can definitely put work cycles towards development... seems like many problems fit into that class.
